services:
  bddban2:
    image: postgres:15
    environment:
      POSTGRES_USER: julie
      POSTGRES_PASSWORD: louvre
      POSTGRES_DB: bddban
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: